base_model: Qwen/Qwen3-1.7B-Base
datasets:
- path: ./data/msmarco_axolotl/train_axolotl.jsonl
  type: chat_template
  chat_template: tokenizer_default_fallback_chatml
  field_messages: conversations
  message_property_mappings:
    role: role
    content: content
  roles:
    assistant:
      - assistant
      - gpt
      - model
    user:
      - user
      - human
    system:
      - system

  roles_to_train: ["assistant"]
  train_on_eos: "turn"

streaming: true
streaming_multipack_buffer_size: 10000
shuffle_merged_datasets: true
output_dir: ./checkpoints/Qwen3-1.7B-Base-msmarco-100k-10epochs
sequence_len: 2048
sample_packing: false
flash_attention: false
xformers_attention: false
flex_attention: false
sdp_attention: true
overrides_of_model_config:
  _attn_implementation: "sdpa"

gradient_accumulation_steps: 8
micro_batch_size: 16
num_epochs: 10

optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.0001
warmup_ratio: 0.1
weight_decay: 0.0
bf16: true
tf32: false
gradient_checkpointing: true

logging_steps: 50
save_strategy: steps
save_steps: 1000
save_total_limit: 5

special_tokens:
  additional_special_tokens:
  - <|d0_0|>
  - <|d0_1|>
  - <|d0_2|>
  - <|d0_3|>
  - <|d0_4|>
  - <|d0_5|>
  - <|d0_6|>
  - <|d0_7|>
  - <|d0_8|>
  - <|d0_9|>
  - <|d0_10|>
  - <|d0_11|>
  - <|d0_12|>
  - <|d0_13|>
  - <|d0_14|>
  - <|d0_15|>
  - <|d0_16|>
  - <|d0_17|>
  - <|d0_18|>
  - <|d0_19|>
  - <|d0_20|>
  - <|d0_21|>
  - <|d0_22|>
  - <|d0_23|>
  - <|d0_24|>
  - <|d0_25|>
  - <|d0_26|>
  - <|d0_27|>
  - <|d0_28|>
  - <|d0_29|>
  - <|d0_30|>
  - <|d0_31|>
  - <|d0_32|>
  - <|d0_33|>
  - <|d0_34|>
  - <|d0_35|>
  - <|d0_36|>
  - <|d0_37|>
  - <|d0_38|>
  - <|d0_39|>
  - <|d0_40|>
  - <|d0_41|>
  - <|d0_42|>
  - <|d0_43|>
  - <|d0_44|>
  - <|d0_45|>
  - <|d0_46|>
  - <|d0_47|>
  - <|d0_48|>
  - <|d0_49|>
  - <|d0_50|>
  - <|d0_51|>
  - <|d0_52|>
  - <|d0_53|>
  - <|d0_54|>
  - <|d0_55|>
  - <|d0_56|>
  - <|d0_57|>
  - <|d0_58|>
  - <|d0_59|>
  - <|d0_60|>
  - <|d0_61|>
  - <|d0_62|>
  - <|d0_63|>
  - <|d0_64|>
  - <|d0_65|>
  - <|d0_66|>
  - <|d0_67|>
  - <|d0_68|>
  - <|d0_69|>
  - <|d0_70|>
  - <|d0_71|>
  - <|d0_72|>
  - <|d0_73|>
  - <|d0_74|>
  - <|d0_75|>
  - <|d0_76|>
  - <|d0_77|>
  - <|d0_78|>
  - <|d0_79|>
  - <|d0_80|>
  - <|d0_81|>
  - <|d0_82|>
  - <|d0_83|>
  - <|d0_84|>
  - <|d0_85|>
  - <|d0_86|>
  - <|d0_87|>
  - <|d0_88|>
  - <|d0_89|>
  - <|d0_90|>
  - <|d0_91|>
  - <|d0_92|>
  - <|d0_93|>
  - <|d0_94|>
  - <|d0_95|>
  - <|d0_96|>
  - <|d0_97|>
  - <|d0_98|>
  - <|d0_99|>
  - <|d0_100|>
  - <|d0_101|>
  - <|d0_102|>
  - <|d0_103|>
  - <|d0_104|>
  - <|d0_105|>
  - <|d0_106|>
  - <|d0_107|>
  - <|d0_108|>
  - <|d0_109|>
  - <|d0_110|>
  - <|d0_111|>
  - <|d0_112|>
  - <|d0_113|>
  - <|d0_114|>
  - <|d0_115|>
  - <|d0_116|>
  - <|d0_117|>
  - <|d0_118|>
  - <|d0_119|>
  - <|d0_120|>
  - <|d0_121|>
  - <|d0_122|>
  - <|d0_123|>
  - <|d0_124|>
  - <|d0_125|>
  - <|d0_126|>
  - <|d0_127|>
  - <|d0_128|>
  - <|d0_129|>
  - <|d0_130|>
  - <|d0_131|>
  - <|d0_132|>
  - <|d0_133|>
  - <|d0_134|>
  - <|d0_135|>
  - <|d0_136|>
  - <|d0_137|>
  - <|d0_138|>
  - <|d0_139|>
  - <|d0_140|>
  - <|d0_141|>
  - <|d0_142|>
  - <|d0_143|>
  - <|d0_144|>
  - <|d0_145|>
  - <|d0_146|>
  - <|d0_147|>
  - <|d0_148|>
  - <|d0_149|>
  - <|d0_150|>
  - <|d0_151|>
  - <|d0_152|>
  - <|d0_153|>
  - <|d0_154|>
  - <|d0_155|>
  - <|d0_156|>
  - <|d0_157|>
  - <|d0_158|>
  - <|d0_159|>
  - <|d0_160|>
  - <|d0_161|>
  - <|d0_162|>
  - <|d0_163|>
  - <|d0_164|>
  - <|d0_165|>
  - <|d0_166|>
  - <|d0_167|>
  - <|d0_168|>
  - <|d0_169|>
  - <|d0_170|>
  - <|d0_171|>
  - <|d0_172|>
  - <|d0_173|>
  - <|d0_174|>
  - <|d0_175|>
  - <|d0_176|>
  - <|d0_177|>
  - <|d0_178|>
  - <|d0_179|>
  - <|d0_180|>
  - <|d0_181|>
  - <|d0_182|>
  - <|d0_183|>
  - <|d0_184|>
  - <|d0_185|>
  - <|d0_186|>
  - <|d0_187|>
  - <|d0_188|>
  - <|d0_189|>
  - <|d0_190|>
  - <|d0_191|>
  - <|d0_192|>
  - <|d0_193|>
  - <|d0_194|>
  - <|d0_195|>
  - <|d0_196|>
  - <|d0_197|>
  - <|d0_198|>
  - <|d0_199|>
  - <|d0_200|>
  - <|d0_201|>
  - <|d0_202|>
  - <|d0_203|>
  - <|d0_204|>
  - <|d0_205|>
  - <|d0_206|>
  - <|d0_207|>
  - <|d0_208|>
  - <|d0_209|>
  - <|d0_210|>
  - <|d0_211|>
  - <|d0_212|>
  - <|d0_213|>
  - <|d0_214|>
  - <|d0_215|>
  - <|d0_216|>
  - <|d0_217|>
  - <|d0_218|>
  - <|d0_219|>
  - <|d0_220|>
  - <|d0_221|>
  - <|d0_222|>
  - <|d0_223|>
  - <|d0_224|>
  - <|d0_225|>
  - <|d0_226|>
  - <|d0_227|>
  - <|d0_228|>
  - <|d0_229|>
  - <|d0_230|>
  - <|d0_231|>
  - <|d0_232|>
  - <|d0_233|>
  - <|d0_234|>
  - <|d0_235|>
  - <|d0_236|>
  - <|d0_237|>
  - <|d0_238|>
  - <|d0_239|>
  - <|d0_240|>
  - <|d0_241|>
  - <|d0_242|>
  - <|d0_243|>
  - <|d0_244|>
  - <|d0_245|>
  - <|d0_246|>
  - <|d0_247|>
  - <|d0_248|>
  - <|d0_249|>
  - <|d0_250|>
  - <|d0_251|>
  - <|d0_252|>
  - <|d0_253|>
  - <|d0_254|>
  - <|d0_255|>
  - <|d1_0|>
  - <|d1_1|>
  - <|d1_2|>
  - <|d1_3|>
  - <|d1_4|>
  - <|d1_5|>
  - <|d1_6|>
  - <|d1_7|>
  - <|d1_8|>
  - <|d1_9|>
  - <|d1_10|>
  - <|d1_11|>
  - <|d1_12|>
  - <|d1_13|>
  - <|d1_14|>
  - <|d1_15|>
  - <|d1_16|>
  - <|d1_17|>
  - <|d1_18|>
  - <|d1_19|>
  - <|d1_20|>
  - <|d1_21|>
  - <|d1_22|>
  - <|d1_23|>
  - <|d1_24|>
  - <|d1_25|>
  - <|d1_26|>
  - <|d1_27|>
  - <|d1_28|>
  - <|d1_29|>
  - <|d1_30|>
  - <|d1_31|>
  - <|d1_32|>
  - <|d1_33|>
  - <|d1_34|>
  - <|d1_35|>
  - <|d1_36|>
  - <|d1_37|>
  - <|d1_38|>
  - <|d1_39|>
  - <|d1_40|>
  - <|d1_41|>
  - <|d1_42|>
  - <|d1_43|>
  - <|d1_44|>
  - <|d1_45|>
  - <|d1_46|>
  - <|d1_47|>
  - <|d1_48|>
  - <|d1_49|>
  - <|d1_50|>
  - <|d1_51|>
  - <|d1_52|>
  - <|d1_53|>
  - <|d1_54|>
  - <|d1_55|>
  - <|d1_56|>
  - <|d1_57|>
  - <|d1_58|>
  - <|d1_59|>
  - <|d1_60|>
  - <|d1_61|>
  - <|d1_62|>
  - <|d1_63|>
  - <|d1_64|>
  - <|d1_65|>
  - <|d1_66|>
  - <|d1_67|>
  - <|d1_68|>
  - <|d1_69|>
  - <|d1_70|>
  - <|d1_71|>
  - <|d1_72|>
  - <|d1_73|>
  - <|d1_74|>
  - <|d1_75|>
  - <|d1_76|>
  - <|d1_77|>
  - <|d1_78|>
  - <|d1_79|>
  - <|d1_80|>
  - <|d1_81|>
  - <|d1_82|>
  - <|d1_83|>
  - <|d1_84|>
  - <|d1_85|>
  - <|d1_86|>
  - <|d1_87|>
  - <|d1_88|>
  - <|d1_89|>
  - <|d1_90|>
  - <|d1_91|>
  - <|d1_92|>
  - <|d1_93|>
  - <|d1_94|>
  - <|d1_95|>
  - <|d1_96|>
  - <|d1_97|>
  - <|d1_98|>
  - <|d1_99|>
  - <|d1_100|>
  - <|d1_101|>
  - <|d1_102|>
  - <|d1_103|>
  - <|d1_104|>
  - <|d1_105|>
  - <|d1_106|>
  - <|d1_107|>
  - <|d1_108|>
  - <|d1_109|>
  - <|d1_110|>
  - <|d1_111|>
  - <|d1_112|>
  - <|d1_113|>
  - <|d1_114|>
  - <|d1_115|>
  - <|d1_116|>
  - <|d1_117|>
  - <|d1_118|>
  - <|d1_119|>
  - <|d1_120|>
  - <|d1_121|>
  - <|d1_122|>
  - <|d1_123|>
  - <|d1_124|>
  - <|d1_125|>
  - <|d1_126|>
  - <|d1_127|>
  - <|d1_128|>
  - <|d1_129|>
  - <|d1_130|>
  - <|d1_131|>
  - <|d1_132|>
  - <|d1_133|>
  - <|d1_134|>
  - <|d1_135|>
  - <|d1_136|>
  - <|d1_137|>
  - <|d1_138|>
  - <|d1_139|>
  - <|d1_140|>
  - <|d1_141|>
  - <|d1_142|>
  - <|d1_143|>
  - <|d1_144|>
  - <|d1_145|>
  - <|d1_146|>
  - <|d1_147|>
  - <|d1_148|>
  - <|d1_149|>
  - <|d1_150|>
  - <|d1_151|>
  - <|d1_152|>
  - <|d1_153|>
  - <|d1_154|>
  - <|d1_155|>
  - <|d1_156|>
  - <|d1_157|>
  - <|d1_158|>
  - <|d1_159|>
  - <|d1_160|>
  - <|d1_161|>
  - <|d1_162|>
  - <|d1_163|>
  - <|d1_164|>
  - <|d1_165|>
  - <|d1_166|>
  - <|d1_167|>
  - <|d1_168|>
  - <|d1_169|>
  - <|d1_170|>
  - <|d1_171|>
  - <|d1_172|>
  - <|d1_173|>
  - <|d1_174|>
  - <|d1_175|>
  - <|d1_176|>
  - <|d1_177|>
  - <|d1_178|>
  - <|d1_179|>
  - <|d1_180|>
  - <|d1_181|>
  - <|d1_182|>
  - <|d1_183|>
  - <|d1_184|>
  - <|d1_185|>
  - <|d1_186|>
  - <|d1_187|>
  - <|d1_188|>
  - <|d1_189|>
  - <|d1_190|>
  - <|d1_191|>
  - <|d1_192|>
  - <|d1_193|>
  - <|d1_194|>
  - <|d1_195|>
  - <|d1_196|>
  - <|d1_197|>
  - <|d1_198|>
  - <|d1_199|>
  - <|d1_200|>
  - <|d1_201|>
  - <|d1_202|>
  - <|d1_203|>
  - <|d1_204|>
  - <|d1_205|>
  - <|d1_206|>
  - <|d1_207|>
  - <|d1_208|>
  - <|d1_209|>
  - <|d1_210|>
  - <|d1_211|>
  - <|d1_212|>
  - <|d1_213|>
  - <|d1_214|>
  - <|d1_215|>
  - <|d1_216|>
  - <|d1_217|>
  - <|d1_218|>
  - <|d1_219|>
  - <|d1_220|>
  - <|d1_221|>
  - <|d1_222|>
  - <|d1_223|>
  - <|d1_224|>
  - <|d1_225|>
  - <|d1_226|>
  - <|d1_227|>
  - <|d1_228|>
  - <|d1_229|>
  - <|d1_230|>
  - <|d1_231|>
  - <|d1_232|>
  - <|d1_233|>
  - <|d1_234|>
  - <|d1_235|>
  - <|d1_236|>
  - <|d1_237|>
  - <|d1_238|>
  - <|d1_239|>
  - <|d1_240|>
  - <|d1_241|>
  - <|d1_242|>
  - <|d1_243|>
  - <|d1_244|>
  - <|d1_245|>
  - <|d1_246|>
  - <|d1_247|>
  - <|d1_248|>
  - <|d1_249|>
  - <|d1_250|>
  - <|d1_251|>
  - <|d1_252|>
  - <|d1_253|>
  - <|d1_254|>
  - <|d1_255|>
  - <|d2_0|>
  - <|d2_1|>
  - <|d2_2|>
  - <|d2_3|>
  - <|d2_4|>
  - <|d2_5|>
  - <|d2_6|>
  - <|d2_7|>
  - <|d2_8|>
  - <|d2_9|>
  - <|d2_10|>
  - <|d2_11|>
  - <|d2_12|>
  - <|d2_13|>
  - <|d2_14|>
  - <|d2_15|>
  - <|d2_16|>
  - <|d2_17|>
  - <|d2_18|>
  - <|d2_19|>
  - <|d2_20|>
  - <|d2_21|>
  - <|d2_22|>
  - <|d2_23|>
  - <|d2_24|>
  - <|d2_25|>
  - <|d2_26|>
  - <|d2_27|>
  - <|d2_28|>
  - <|d2_29|>
  - <|d2_30|>
  - <|d2_31|>
  - <|d2_32|>
  - <|d2_33|>
  - <|d2_34|>
  - <|d2_35|>
  - <|d2_36|>
  - <|d2_37|>
  - <|d2_38|>
  - <|d2_39|>
  - <|d2_40|>
  - <|d2_41|>
  - <|d2_42|>
  - <|d2_43|>
  - <|d2_44|>
  - <|d2_45|>
  - <|d2_46|>
  - <|d2_47|>
  - <|d2_48|>
  - <|d2_49|>
  - <|d2_50|>
  - <|d2_51|>
  - <|d2_52|>
  - <|d2_53|>
  - <|d2_54|>
  - <|d2_55|>
  - <|d2_56|>
  - <|d2_57|>
  - <|d2_58|>
  - <|d2_59|>
  - <|d2_60|>
  - <|d2_61|>
  - <|d2_62|>
  - <|d2_63|>
  - <|d2_64|>
  - <|d2_65|>
  - <|d2_66|>
  - <|d2_67|>
  - <|d2_68|>
  - <|d2_69|>
  - <|d2_70|>
  - <|d2_71|>
  - <|d2_72|>
  - <|d2_73|>
  - <|d2_74|>
  - <|d2_75|>
  - <|d2_76|>
  - <|d2_77|>
  - <|d2_78|>
  - <|d2_79|>
  - <|d2_80|>
  - <|d2_81|>
  - <|d2_82|>
  - <|d2_83|>
  - <|d2_84|>
  - <|d2_85|>
  - <|d2_86|>
  - <|d2_87|>
  - <|d2_88|>
  - <|d2_89|>
  - <|d2_90|>
  - <|d2_91|>
  - <|d2_92|>
  - <|d2_93|>
  - <|d2_94|>
  - <|d2_95|>
  - <|d2_96|>
  - <|d2_97|>
  - <|d2_98|>
  - <|d2_99|>
  - <|d2_100|>
  - <|d2_101|>
  - <|d2_102|>
  - <|d2_103|>
  - <|d2_104|>
  - <|d2_105|>
  - <|d2_106|>
  - <|d2_107|>
  - <|d2_108|>
  - <|d2_109|>
  - <|d2_110|>
  - <|d2_111|>
  - <|d2_112|>
  - <|d2_113|>
  - <|d2_114|>
  - <|d2_115|>
  - <|d2_116|>
  - <|d2_117|>
  - <|d2_118|>
  - <|d2_119|>
  - <|d2_120|>
  - <|d2_121|>
  - <|d2_122|>
  - <|d2_123|>
  - <|d2_124|>
  - <|d2_125|>
  - <|d2_126|>
  - <|d2_127|>
  - <|d2_128|>
  - <|d2_129|>
  - <|d2_130|>
  - <|d2_131|>
  - <|d2_132|>
  - <|d2_133|>
  - <|d2_134|>
  - <|d2_135|>
  - <|d2_136|>
  - <|d2_137|>
  - <|d2_138|>
  - <|d2_139|>
  - <|d2_140|>
  - <|d2_141|>
  - <|d2_142|>
  - <|d2_143|>
  - <|d2_144|>
  - <|d2_145|>
  - <|d2_146|>
  - <|d2_147|>
  - <|d2_148|>
  - <|d2_149|>
  - <|d2_150|>
  - <|d2_151|>
  - <|d2_152|>
  - <|d2_153|>
  - <|d2_154|>
  - <|d2_155|>
  - <|d2_156|>
  - <|d2_157|>
  - <|d2_158|>
  - <|d2_159|>
  - <|d2_160|>
  - <|d2_161|>
  - <|d2_162|>
  - <|d2_163|>
  - <|d2_164|>
  - <|d2_165|>
  - <|d2_166|>
  - <|d2_167|>
  - <|d2_168|>
  - <|d2_169|>
  - <|d2_170|>
  - <|d2_171|>
  - <|d2_172|>
  - <|d2_173|>
  - <|d2_174|>
  - <|d2_175|>
  - <|d2_176|>
  - <|d2_177|>
  - <|d2_178|>
  - <|d2_179|>
  - <|d2_180|>
  - <|d2_181|>
  - <|d2_182|>
  - <|d2_183|>
  - <|d2_184|>
  - <|d2_185|>
  - <|d2_186|>
  - <|d2_187|>
  - <|d2_188|>
  - <|d2_189|>
  - <|d2_190|>
  - <|d2_191|>
  - <|d2_192|>
  - <|d2_193|>
  - <|d2_194|>
  - <|d2_195|>
  - <|d2_196|>
  - <|d2_197|>
  - <|d2_198|>
  - <|d2_199|>
  - <|d2_200|>
  - <|d2_201|>
  - <|d2_202|>
  - <|d2_203|>
  - <|d2_204|>
  - <|d2_205|>
  - <|d2_206|>
  - <|d2_207|>
  - <|d2_208|>
  - <|d2_209|>
  - <|d2_210|>
  - <|d2_211|>
  - <|d2_212|>
  - <|d2_213|>
  - <|d2_214|>
  - <|d2_215|>
  - <|d2_216|>
  - <|d2_217|>
  - <|d2_218|>
  - <|d2_219|>
  - <|d2_220|>
  - <|d2_221|>
  - <|d2_222|>
  - <|d2_223|>
  - <|d2_224|>
  - <|d2_225|>
  - <|d2_226|>
  - <|d2_227|>
  - <|d2_228|>
  - <|d2_229|>
  - <|d2_230|>
  - <|d2_231|>
  - <|d2_232|>
  - <|d2_233|>
  - <|d2_234|>
  - <|d2_235|>
  - <|d2_236|>
  - <|d2_237|>
  - <|d2_238|>
  - <|d2_239|>
  - <|d2_240|>
  - <|d2_241|>
  - <|d2_242|>
  - <|d2_243|>
  - <|d2_244|>
  - <|d2_245|>
  - <|d2_246|>
  - <|d2_247|>
  - <|d2_248|>
  - <|d2_249|>
  - <|d2_250|>
  - <|d2_251|>
  - <|d2_252|>
  - <|d2_253|>
  - <|d2_254|>
  - <|d2_255|>
  - <|d3_0|>
  - <|d3_1|>
  - <|d3_2|>
  - <|d3_3|>
  - <|d3_4|>
  - <|d3_5|>
  - <|d3_6|>
  - <|d3_7|>
  - <|d3_8|>
  - <|d3_9|>
  - <|d3_10|>
  - <|d3_11|>
  - <|d3_12|>
  - <|d3_13|>
  - <|d3_14|>
  - <|d3_15|>
  - <|d3_16|>
  - <|d3_17|>
  - <|d3_18|>
  - <|d3_19|>
  - <|d3_20|>
  - <|d3_21|>
  - <|d3_22|>
  - <|d3_23|>
  - <|d3_24|>
  - <|d3_25|>
  - <|d3_26|>
  - <|d3_27|>
  - <|d3_28|>
  - <|d3_29|>
  - <|d3_30|>
  - <|d3_31|>
  - <|d3_32|>
  - <|d3_33|>
  - <|d3_34|>
  - <|d3_35|>
  - <|d3_36|>
  - <|d3_37|>
  - <|d3_38|>
  - <|d3_39|>
  - <|d3_40|>
  - <|d3_41|>
  - <|d3_42|>
  - <|d3_43|>
  - <|d3_44|>
  - <|d3_45|>
  - <|d3_46|>
  - <|d3_47|>
  - <|d3_48|>
  - <|d3_49|>
  - <|d3_50|>
  - <|d3_51|>
  - <|d3_52|>
  - <|d3_53|>
  - <|d3_54|>
  - <|d3_55|>
  - <|d3_56|>
  - <|d3_57|>
  - <|d3_58|>
  - <|d3_59|>
  - <|d3_60|>
  - <|d3_61|>
  - <|d3_62|>
  - <|d3_63|>
  - <|d3_64|>
  - <|d3_65|>
  - <|d3_66|>
  - <|d3_67|>
  - <|d3_68|>
  - <|d3_69|>
  - <|d3_70|>
  - <|d3_71|>
  - <|d3_72|>
  - <|d3_73|>
  - <|d3_74|>
  - <|d3_75|>
  - <|d3_76|>
  - <|d3_77|>
  - <|d3_78|>
  - <|d3_79|>
  - <|d3_80|>
  - <|d3_81|>
  - <|d3_82|>
  - <|d3_83|>
  - <|d3_84|>
  - <|d3_85|>
  - <|d3_86|>
  - <|d3_87|>
  - <|d3_88|>
  - <|d3_89|>
  - <|d3_90|>
  - <|d3_91|>
  - <|d3_92|>
  - <|d3_93|>
  - <|d3_94|>
  - <|d3_95|>
  - <|d3_96|>
  - <|d3_97|>
  - <|d3_98|>
  - <|d3_99|>
  - <|d3_100|>
  - <|d3_101|>
  - <|d3_102|>
  - <|d3_103|>
  - <|d3_104|>
  - <|d3_105|>
  - <|d3_106|>
  - <|d3_107|>
  - <|d3_108|>
  - <|d3_109|>
  - <|d3_110|>
  - <|d3_111|>
  - <|d3_112|>
  - <|d3_113|>
  - <|d3_114|>
  - <|d3_115|>
  - <|d3_116|>
  - <|d3_117|>
  - <|d3_118|>
  - <|d3_119|>
  - <|d3_120|>
  - <|d3_121|>
  - <|d3_122|>
  - <|d3_123|>
  - <|d3_124|>
  - <|d3_125|>
  - <|d3_126|>
  - <|d3_127|>
  - <|d3_128|>
  - <|d3_129|>
  - <|d3_130|>
  - <|d3_131|>
  - <|d3_132|>
  - <|d3_133|>
  - <|d3_134|>
  - <|d3_135|>
  - <|d3_136|>
  - <|d3_137|>
  - <|d3_138|>
  - <|d3_139|>
  - <|d3_140|>
  - <|d3_141|>
  - <|d3_142|>
  - <|d3_143|>
  - <|d3_144|>
  - <|d3_145|>
  - <|d3_146|>
  - <|d3_147|>
  - <|d3_148|>
  - <|d3_149|>
  - <|d3_150|>
  - <|d3_151|>
  - <|d3_152|>
  - <|d3_153|>
  - <|d3_154|>
  - <|d3_155|>
  - <|d3_156|>
  - <|d3_157|>
  - <|d3_158|>
  - <|d3_159|>
  - <|d3_160|>
  - <|d3_161|>
  - <|d3_162|>
  - <|d3_163|>
  - <|d3_164|>
  - <|d3_165|>
  - <|d3_166|>
  - <|d3_167|>
  - <|d3_168|>
  - <|d3_169|>
  - <|d3_170|>
  - <|d3_171|>
  - <|d3_172|>
  - <|d3_173|>
  - <|d3_174|>
  - <|d3_175|>
  - <|d3_176|>
  - <|d3_177|>
  - <|d3_178|>
  - <|d3_179|>
  - <|d3_180|>
  - <|d3_181|>
  - <|d3_182|>
  - <|d3_183|>
  - <|d3_184|>
  - <|d3_185|>
  - <|d3_186|>
  - <|d3_187|>
  - <|d3_188|>
  - <|d3_189|>
  - <|d3_190|>
  - <|d3_191|>
  - <|d3_192|>
  - <|d3_193|>
  - <|d3_194|>
  - <|d3_195|>
  - <|d3_196|>
  - <|d3_197|>
  - <|d3_198|>
  - <|d3_199|>
  - <|d3_200|>
  - <|d3_201|>
  - <|d3_202|>
  - <|d3_203|>
  - <|d3_204|>
  - <|d3_205|>
  - <|d3_206|>
  - <|d3_207|>
  - <|d3_208|>
  - <|d3_209|>
  - <|d3_210|>
  - <|d3_211|>
  - <|d3_212|>
  - <|d3_213|>
  - <|d3_214|>
  - <|d3_215|>
  - <|d3_216|>
  - <|d3_217|>
  - <|d3_218|>
  - <|d3_219|>
  - <|d3_220|>
  - <|d3_221|>
  - <|d3_222|>
  - <|d3_223|>
  - <|d3_224|>
  - <|d3_225|>
  - <|d3_226|>
  - <|d3_227|>
  - <|d3_228|>
  - <|d3_229|>
  - <|d3_230|>
  - <|d3_231|>
  - <|d3_232|>
  - <|d3_233|>
  - <|d3_234|>
  - <|d3_235|>
  - <|d3_236|>
  - <|d3_237|>
  - <|d3_238|>
  - <|d3_239|>
  - <|d3_240|>
  - <|d3_241|>
  - <|d3_242|>
  - <|d3_243|>
  - <|d3_244|>
  - <|d3_245|>
  - <|d3_246|>
  - <|d3_247|>
  - <|d3_248|>
  - <|d3_249|>
  - <|d3_250|>
  - <|d3_251|>
  - <|d3_252|>
  - <|d3_253|>
  - <|d3_254|>
  - <|d3_255|>
  eos_token: "<|im_end|>"
val_set_size: 0.0
wandb_project: ICLGR-MSMARCO
wandb_entity: abnerden0803-national-taiwan-university
wandb_watch:
wandb_name: qwen3-1.7b-base-msmarco-100k-10epochs
wandb_log_model:
